doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                        # configure these for your database server
                        driver: 'pdo_postgresql'
                        server_version: '12'
                        charset: utf8
                        default_table_options:
                            charset: utf8
                            collate: utf8_unicode_ci
                        url: '%env(resolve:DATABASE_URL)%'
            it:
                        # configure these for your database server
                        driver: 'pdo_postgresql'
                        server_version: '12'
                        charset: utf8
                        default_table_options:
                            charset: utf8
                            collate: utf8_unicode_ci
                        url: '%env(resolve:DATABASE_URL_IT)%'
    orm:
        auto_generate_proxy_classes: true
       # naming_strategy: doctrine.orm.naming_strategy.underscore
       # auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                     App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            it:
                connection: it
                mappings:
                    italie:
                            is_bundle: false
                            type: annotation
                            dir: '%kernel.project_dir%/src/Entity'
                            prefix: 'App\Entity'
                            alias: italie